#ifndef IOAM_TRACE_INTEGRITY_H
#define IOAM_TRACE_INTEGRITY_H

#include <ioam/encap/ip6_ioam_trace.h>
#include <ioam/ioam-crypto/crypto.h>
/*
    0                   1                   2                   3
    0 1 2 3 4 5 6 7 8 9 0 1 2 3 4 5 6 7 8 9 0 1 2 3 4 5 6 7 8 9 0 1
   +-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+
   |Signature-suite|  Nonce length |           Reserved            |
   +-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+
   |                             Nonce                             ~
   +-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+
   |                           Signature                           ~
   +-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+

   Signature-suite:  8-bit unsigned integer.  This field defines the
      algorithms used to compute the digest and the signature over the
      IOAM-Data-Fields.

   Nonce length:  8-bit unsigned integer.  This field specifies the
      length of the Nonce in octets.

   Reserved:  16-bit Reserved field.  MUST be set to zero upon
      transmission and ignored upon receipt.

   Nonce:  Variable length field with length specified in Nonce length.

   Signature:  Digital signature value generated by the method and
      algorithm specified by Signature-suite.

*/

#define MAX_NODE 20

typedef CLIB_PACKED(
    struct ioam_trace_integrity
    {
        u8 signature_suite;
        u8 nonce_len;
        u32 nonce;
        u32* signature;
        u32* cp_data;
    }
) ioam_trace_integrity_t;

void checkForInterity(ioam_trace_option_t *, int* );

#endif